### ISSUE TITLE
Opportunity responses = orders: to be implemented and to be fully explored 

### ISSUE THREAD

**Issue by nic-planet** [Element84/stat-api-spec#78]
Having the opportunities endpoint accept order-like data structures and also _return_ order-like data structures such that an opportunity can be ordered just by picking the corresponding response and sending it to the orders endpoint is a super-elegant idea. This is mostly a reminder that at least the Planet backend plugin does not work like that yet. This looks like it could be a great topic for a future sprint, thinking through a bunch of scenarios to make sure this can work in all cases.

**Comment by jsignell** [comment]
Yeah, as the spec is currently defined the input to `/opportunities` and `/orders` are exactly the same. I totally agree that it would be very cool if the output from `/opportunities` was simply a list where each item in the list was a valid input. The spec people ended up going away from that idea partially because they wanted the output of `/opportunities` to be valid geojson but maybe there is an opportunity here for there to be a format flag. So you could specify something like `/opportunities?f=geojson` and get an OpportunityCollection or you could specify `/opportunities?f={somethingelse}` and get back a list of valid inputs.

**Comment by matthewhanson** [comment]
This is no longer relevant as it is handled by providing a link with `rel=order` for each opportunity. This provides the exact method for how an opportunity gets ordered without having to worry about parity between the order request and the opportunity response which is awkward at best.
